#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fnilsson <filip.c.nilsson@gmail.com>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/03 14:15:41 by fnilsson          #+#    #+#              #
#    Updated: 2018/07/03 23:33:31 by fnilsson         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME=do-op
SRCS=srcs/ft_main.c srcs/ft_functions.c srcs/ft_math.c

all:
	gcc $(SRCS) -o $(NAME)

clean:
	/bin/rm -f $(NAME)

re: clean all